### ISSUE TITLE
Remove tewan's entry from `https://portal2communityedition.com/team`

### ISSUE THREAD

**Issue by hexaflexahexagon** [ChaosInitiative/ChaosWeb#6]
might wanna add a section to the "contributors" section below with something like "Ex-Team Member" to ack the work he did for the project, depends how the page is supposed to be organized.

**Comment by JJL772** [comment]
That's been done on master already, a rework of the "Contributors" list is coming soon:tm:

**Comment by ThePiGuy24** [comment]
Change is live now
